### ISSUE TITLE
minimalkb --version throws exception:  object has no attribute 'version'

### ISSUE THREAD

**Issue by slowrunner** [severin-lemaignan/minimalkb#7]
(sorry... this is not a critical issue)

--help works:
```
pi@Carl:~/Carl/Examples/minimalkb/testing $ minimalkb --help
minimalKB 1.0
usage: minimalkb [-h] [-v] [-q] [-d] [-p [PORT]] [ontology [ontology ...]]

A minimal knowledge base for robots.

positional arguments:
  ontology              Files (OWL, RDF or raw triples) with initial
                        ontologies to load

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         returns minimalKB version
  -q, --quiet           be quiet (only errors are reported)
  -d, --debug           enables verbose output
  -p [PORT], --port [PORT]
                        port the server listen to.
```

but --version throws error:

```
$ minimalkb --version
minimalKB 1.0
Traceback (most recent call last):
  File "/usr/local/bin/minimalkb", line 113, in <module>
    args = parser.parse_args()
  File "/usr/lib/python3.7/argparse.py", line 1758, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1790, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1996, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.7/argparse.py", line 1936, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1864, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.7/argparse.py", line 1069, in __call__
    version = parser.version
AttributeError: 'ArgumentParser' object has no attribute 'version'
```

**Comment by severin-lemaignan** [comment]
Thanks for reporting! Fixed pushed :-)
